import serial
import threading

# Constants from KERN-LITE spec
STX = b'\xAB' # [cite: 277]
BAUD = 115200 # 

# Update GS_PORT to the second PTY generated by socat
# Update BOARD_PORT to the real STM32 Nucleo port
GS_PORT = '/dev/pts/12'
BOARD_PORT = '/dev/ttyACM0' 

gs = serial.Serial(GS_PORT, BAUD, timeout=0.1)
board = serial.Serial(BOARD_PORT, BAUD, timeout=0.1)

def proxy(src, dst, direction):
    inject_malform = True if direction == "GS2B" else False
    inject_corrupt = True if direction == "B2GS" else False
    
    while True:
        data = src.read(src.in_waiting or 1)
        if not data:
            continue
            
        if inject_malform and STX in data:
            # T6: send a malformed GS-to-board frame 
            # Action: Scramble the STX header byte
            data = data.replace(STX, b'\xFF', 1) 
            inject_malform = False
            print("[*] GS->Board: Injected malformed frame (STX stripped)")
            
        if inject_corrupt and STX in data:
            # T6: inject one corrupted board-to-GS byte stream [cite: 1260]
            # Action: Flip a byte in the payload (offset +5)
            idx = data.find(STX)
            if len(data) > idx + 5: 
                data = data[:idx+5] + bytes([data[idx+5] ^ 0xFF]) + data[idx+6:]
                inject_corrupt = False
                print("[*] Board->GS: Injected payload CRC corruption")
                
        dst.write(data)

threading.Thread(target=proxy, args=(gs, board, "GS2B"), daemon=True).start()
proxy(board, gs, "B2GS")
